import type { Metadata } from "next";
import "./globals.css";
import { Nunito } from "next/font/google";

import { Header } from "@/components/shared";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const nunito = Nunito({
  subsets: ["cyrillic"],
  weight: ["400", "500", "600", "700", "800", "900"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${nunito.className}`}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
